name: Check code on PR
on: 
  pull_request: 
  workflow_dispatch: 
permissions: 
    contents: read
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
jobs:
    changes:
      runs-on: ubuntu-latest
      permissions: 
        pull-requests: read
      outputs:
        components-changed: ${{ steps.changes.outputs.changes }}
      steps:
        - name: Paths Changes Filter
          uses: dorny/paths-filter@v4.0.3
          id: changes
          with:
            filters: |
              download:
              - 'download/**'
              embed:
                - 'embed/**'
              backend:
                - 'backend/**'
              frontend:
                - 'frontend/**'
              speakers:
                - 'speakers/**'
              orchestrator:
                - 'orchestrator/**'
    python_check:
      needs: changes
      runs-on: ubuntu-latest
      steps:
        - name: Show filters output
          run: echo " ${{ toJson(needs.changes.outputs.components-changed) }} "