name: Check code on PR
on: 
  pull_request: 
permissions: 
    contents: read
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    changes:
      runs-on: ubuntu-latest
      permissions: 
        pull-requests: read
      outputs:
        python-changed: ${{ steps.changes-python.outputs.changes }}
        js-changed: ${{ steps.changes-js.outputs.changes }}
      steps:
        - name: Paths python changes filter
          uses: dorny/paths-filter@v4.0.3
          id: changes-python
          with:
            filters: |
              download:
              - 'download/**'
              embed:
                - 'embed/**'
              backend:
                - 'backend/**'
              orchestrator:
                - 'orchestrator/**'
        - name: Paths js changes filter
          uses: dorny/paths-filter@v4.0.3
          id: changes-js
          with: 
            filters: |
              frontend:
                - 'frontend/**'
              speakers:
                - 'speakers/**'
    python-check:
      needs: changes
      if: ${{ fromJson(needs.changes.outputs.python-changed) != '[]' }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          components: ${{ fromJson(needs.changes.outputs.python-changed) }}
      defaults:
        run:
          working-directory: ${{ matrix.components }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v7
        - name: Setup uv
          uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
          id: setup-uv
          with:
            version: "0.10.7"
            enable-cache: true
            working-directory: ${{matrix.components}}
        - name: Install dependencies
          run: uv sync --locked
        - name: Run checks
          run: | 
            uv run --no-sync pytest 
            uv run --no-sync ruff check 
            uv run --no-sync ruff format --check 
    js-check:
      needs: changes
      if: ${{ fromJson(needs.changes.outputs.js-changed) != '[]' }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          components: ${{ fromJson(needs.changes.outputs.js-changed) }}
      defaults:
        run:
          working-directory: ${{ matrix.components }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v7
        - name: Setup bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version-file: ${{ matrix.components }}/package.json
        - name: Cache dependencies
          uses: actions/cache@v6
          id: cache
          with:
            path: |
              ~/.bun/install/cache
            key: ${{ matrix.components }}-bun-${{ hashFiles(format('{0}/bun.lock', matrix.components)) }}
        - name: Install dependencies
          run: bun ci
        - name: Run checks
          run: |
            bun test
            bun run lint
            bun run format:check
            bun run build